name: Web Automation Workflow

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # download repo
    - uses: actions/checkout@v4

    # setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    # install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v2.1.2

    # setup gradle
    - name: Setup Gradlew
      run: chmod +x gradlew

    # execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew clean test
  
   
